
// This file is automatically generated. Do not edit it directly.
import { supabase } from '@/lib/supabase';
import type { Database } from './types';

// Re-export the single Supabase instance to prevent multiple clients
export { supabase };
