
// This file is automatically generated. Do not edit it directly.
import { supabase } from '@/lib/supabase';

// Re-export the single Supabase instance to prevent multiple clients
export { supabase };
